### ISSUE TITLE
Not accepting * as any for network security groups

### ISSUE THREAD

**Issue by milan21984** [Azure/terraform-azurerm-network-security-group#44]
Hello team, 

I recently started using this module wintin Terraform and when I use following variable, Azure portal is showing warning for port range. 
destination_port_range = "*"
I'm certain that it take "*" as an input but it Azure shows 0-65535 instead of "*". 

Also, edit the readme for under Usage with the pre-defined module. 
source_address_prefix  = ["VirtualNetwork"] doesn't require square brackets when specifying CIDR range.

**Comment by yupwei68** [comment]
Hi @milan21984 . I suppose you mean  destination_port_range = "*" in line 3 and line 4? on fact, we use "destination_port_ranges" instead of "destination_port_range", which doesn't take "*" as a valid value. We do an internal replacement in the module. Currently, 0-65535 and "*" work the same.

Thanks for the second remind. I'll change it later.

**Comment by yupwei68** [comment]
Hi @milan21984 ,Thanks for opening this issue. We have fixed it in the latest release v3.0.0
